// ********************************************************
// The use of this source code is licensed under the terms
// of the MIT License (https://opensource.org/licenses/MIT)
// ********************************************************

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Baselines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Baselines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.Baselines", typeof(Baselines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000,06/12/2022 18:00:00.212,3877.50,3880.00,3874.50,3874.50
        ///0001,06/12/2022 18:00:00.212,3876.00,3876.00,3873.00,3873.00
        ///0002,06/12/2022 18:00:00.548,3874.50,3875.75,3871.50,3871.50
        ///0003,06/12/2022 18:00:09.408,3873.00,3875.25,3870.00,3870.00
        ///0004,06/12/2022 18:00:10.092,3871.50,3871.50,3868.50,3868.50
        ///0005,06/12/2022 18:00:28.508,3870.00,3873.00,3867.75,3873.00
        ///0006,06/12/2022 18:00:29.196,3871.50,3874.50,3871.50,3874.50
        ///0007,06/12/2022 18:00:35.500,3873.00,3876.00,3872.25,3876.00
        ///0008,06/12/2022  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TdRenkoFeedBaselines {
            get {
                return ResourceManager.GetString("TdRenkoFeedBaselines", resourceCulture);
            }
        }
    }
}