// ********************************************************
// The use of this source code is licensed under the terms
// of the MIT License (https://opensource.org/licenses/MIT)
// ********************************************************

namespace SquidEyes.UnitTests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Baselines {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Baselines() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SquidEyes.UnitTests.Properties.Baselines", typeof(Baselines).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,3.574667799777445
        ///12/15/2019 18:00:00.166,3.555186444197161
        ///12/15/2019 18:00:00.242,3.6168738268857346
        ///12/15/2019 18:00:00.242,3.6854153632063715
        ///12/15/2019 18:00:00.308,3.761572625784857
        ///12/15/2019 18:00:00.308,3.6239695842053967
        ///12/15/2019 18:00:00.308,3.6932995380059963
        ///12/15/2019 18:00:00.360,3.770332820006663
        ///12/15/2019 18:00:00.366,3.633703133340737
        ///12/15/2019 18:00:00.693,3.7041145926008183
        ///12/15/2019 18:00:01.198,3.7545717695564647
        ///12/15/2019 18:00:01.198,3.7273019 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AtrIndicatorBaselines {
            get {
                return ResourceManager.GetString("AtrIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536.990244424858
        ///12/15/2019 18:00:00.166,8537.367199783159
        ///12/15/2019 18:00:00.242,8537.418200776638
        ///12/15/2019 18:00:00.242,8537.029363449223
        ///12/15/2019 18:00:00.308,8536.051947687942
        ///12/15/2019 18:00:00.308,8536.070653076926
        ///12/15/2019 18:00:00.308,8536.539695774578
        ///12/15/2019 18:00:00.360,8537.608846918929
        ///12/15/2019 18:00:00.366,8537.694233039801
        ///12/15/2019 18:00:00.693,8537.343081701423
        ///12/15/2019 18:00:01.198,8536.406518260075
        ///12/15/2019 18:00:01.198,8536.4688608595 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DemaIndicatorBaselines {
            get {
                return ResourceManager.GetString("DemaIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536.705582600345
        ///12/15/2019 18:00:00.166,8536.862378733755
        ///12/15/2019 18:00:00.242,8536.831796230144
        ///12/15/2019 18:00:00.242,8536.572195392398
        ///12/15/2019 18:00:00.308,8536.032683257377
        ///12/15/2019 18:00:00.308,8536.03994620346
        ///12/15/2019 18:00:00.308,8536.271045359787
        ///12/15/2019 18:00:00.360,8536.775722106406
        ///12/15/2019 18:00:00.366,8536.725882574496
        ///12/15/2019 18:00:00.693,8536.442745368828
        ///12/15/2019 18:00:01.198,8535.874466561901
        ///12/15/2019 18:00:01.198,8535.84657024232 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string EmaIndicatorBaselines {
            get {
                return ResourceManager.GetString("EmaIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536
        ///12/15/2019 18:00:00.166,8537
        ///12/15/2019 18:00:00.242,8538
        ///12/15/2019 18:00:00.242,8539
        ///12/15/2019 18:00:00.308,8536
        ///12/15/2019 18:00:00.308,8535
        ///12/15/2019 18:00:00.308,8534
        ///12/15/2019 18:00:00.360,8537
        ///12/15/2019 18:00:00.366,8538
        ///12/15/2019 18:00:00.693,8539
        ///12/15/2019 18:00:01.198,8536
        ///12/15/2019 18:00:01.198,8539
        ///12/15/2019 18:00:02.416,8536
        ///12/15/2019 18:00:02.416,8535
        ///12/15/2019 18:00:02.416,8534
        ///12/15/2019 18:00:02.456,8537
        ///12/15/2019 18:00:03.173,8538
        ///12 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KamaIndicatorBaselines {
            get {
                return ResourceManager.GetString("KamaIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None,8536,8536,8536,8536,None,None
        ///None,8537,8537,8537,8537,None,None
        ///None,8538,8538,8538,8538,None,None
        ///None,8539,8539,8539,8539,None,None
        ///None,8536,8536,8536,8536,None,None
        ///None,8535,8535,8535,8535,None,None
        ///None,8534,8534,8534,8534,None,None
        ///None,8537,8537,8537,8537,None,None
        ///None,8538,8538,8538,8538,None,None
        ///None,8539,8539,8539,8539,None,None
        ///None,8536,8536,8536,8536,None,None
        ///None,8539,8539,8539,8539,None,None
        ///None,8536,8536,8536,8536,None,None
        ///None,8535,8535,8535,8535,None,None
        ///None,853 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string KdsIndicatorBaselines {
            get {
                return ResourceManager.GetString("KdsIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536.9
        ///12/15/2019 18:00:00.166,8536.9
        ///12/15/2019 18:00:00.242,8537.1
        ///12/15/2019 18:00:00.242,8536.9
        ///12/15/2019 18:00:00.308,8536.5
        ///12/15/2019 18:00:00.308,8536.3
        ///12/15/2019 18:00:00.308,8536.5
        ///12/15/2019 18:00:00.360,8536.9
        ///12/15/2019 18:00:00.366,8536.7
        ///12/15/2019 18:00:00.693,8536.3
        ///12/15/2019 18:00:01.198,8535.7
        ///12/15/2019 18:00:01.198,8535.3
        ///12/15/2019 18:00:02.416,8534.5
        ///12/15/2019 18:00:02.416,8534.3
        ///12/15/2019 18:00:02.416,8534.3
        ///12/15/2019 18:00:02.456,8534.1
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmaIndicatorBaselines {
            get {
                return ResourceManager.GetString("SmaIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536.598666958696
        ///12/15/2019 18:00:00.166,8536.667806529309
        ///12/15/2019 18:00:00.242,8536.644217352507
        ///12/15/2019 18:00:00.242,8536.524326473043
        ///12/15/2019 18:00:00.308,8536.247561740714
        ///12/15/2019 18:00:00.308,8536.262770804724
        ///12/15/2019 18:00:00.308,8536.373450969368
        ///12/15/2019 18:00:00.360,8536.6401002923
        ///12/15/2019 18:00:00.366,8536.613707355278
        ///12/15/2019 18:00:00.693,8536.49134408077
        ///12/15/2019 18:00:01.198,8536.206320906604
        ///12/15/2019 18:00:01.198,8536.262873554884
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SmmaIndicatorBaselines {
            get {
                return ResourceManager.GetString("SmmaIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,1.57797338380595
        ///12/15/2019 18:00:00.166,1.57797338380595
        ///12/15/2019 18:00:00.242,1.7
        ///12/15/2019 18:00:00.242,1.7
        ///12/15/2019 18:00:00.308,1.6278820596099706
        ///12/15/2019 18:00:00.308,1.7916472867168918
        ///12/15/2019 18:00:00.308,1.746424919657298
        ///12/15/2019 18:00:00.360,1.57797338380595
        ///12/15/2019 18:00:00.366,1.676305461424021
        ///12/15/2019 18:00:00.693,1.7916472867168918
        ///12/15/2019 18:00:01.198,1.7916472867168916
        ///12/15/2019 18:00:01.198,2.0999999999999996
        ///12/15/2019 18:00:02.41 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StdDevIndicatorBaselines {
            get {
                return ResourceManager.GetString("StdDevIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SwingIndicatorBaselines {
            get {
                return ResourceManager.GetString("SwingIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0000,12/15/2019 18:00:00.166,8534.00,8536.00,8533.25,8536.00
        ///0001,12/15/2019 18:00:00.166,8535.00,8537.00,8535.00,8537.00
        ///0002,12/15/2019 18:00:00.242,8536.00,8538.00,8536.00,8538.00
        ///0003,12/15/2019 18:00:00.242,8537.00,8539.00,8537.00,8539.00
        ///0004,12/15/2019 18:00:00.308,8538.00,8540.00,8536.00,8536.00
        ///0005,12/15/2019 18:00:00.308,8537.00,8537.00,8535.00,8535.00
        ///0006,12/15/2019 18:00:00.308,8536.00,8536.00,8534.00,8534.00
        ///0007,12/15/2019 18:00:00.360,8535.00,8537.00,8533.00,8537.00
        ///0008,12/15/2019  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TdRenkoFeedBaselines {
            get {
                return ResourceManager.GetString("TdRenkoFeedBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536.958916237132
        ///12/15/2019 18:00:00.166,8537.549178873158
        ///12/15/2019 18:00:00.242,8537.72221688664
        ///12/15/2019 18:00:00.242,8537.271815430886
        ///12/15/2019 18:00:00.308,8535.910343859978
        ///12/15/2019 18:00:00.308,8535.908866453852
        ///12/15/2019 18:00:00.308,8536.580020804715
        ///12/15/2019 18:00:00.360,8538.222803205763
        ///12/15/2019 18:00:00.366,8538.57982370982
        ///12/15/2019 18:00:00.693,8538.357327937001
        ///12/15/2019 18:00:01.198,8537.27787997856
        ///12/15/2019 18:00:01.198,8537.62391927935
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemaIndicatorBaselines {
            get {
                return ResourceManager.GetString("TemaIndicatorBaselines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12/15/2019 18:00:00.166,8536.781818181818
        ///12/15/2019 18:00:00.166,8536.945454545454
        ///12/15/2019 18:00:00.242,8536.963636363636
        ///12/15/2019 18:00:00.242,8536.763636363636
        ///12/15/2019 18:00:00.308,8536.309090909092
        ///12/15/2019 18:00:00.308,8536.363636363636
        ///12/15/2019 18:00:00.308,8536.636363636364
        ///12/15/2019 18:00:00.360,8537.163636363637
        ///12/15/2019 18:00:00.366,8537.10909090909
        ///12/15/2019 18:00:00.693,8536.8
        ///12/15/2019 18:00:01.198,8536.2
        ///12/15/2019 18:00:01.198,8536.072727272727
        ///12/15/2019 18:00:02 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WmaIndicatorBaselines {
            get {
                return ResourceManager.GetString("WmaIndicatorBaselines", resourceCulture);
            }
        }
    }
}